name: Release Application
on:
    push:
        paths:
            - 'version'

    workflow_dispatch:

jobs:
    publish:
        name: Build & Release app
        runs-on: ubuntu-latest
        steps:
            - name: Clone codebase
              uses: actions/checkout@v4

            - name: Get tag name
              id: tag
              run: echo "version=$(cat version)" >> $GITHUB_OUTPUT

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install project dependencies
              run: npm install

            - name: Install packager
              run: npm install -g pkg

            - name: Package application
              run: pkg -t latest-linux-x64 wallhaven-cli.mjs

            - name: Release asset
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.tag.outputs.version }}
                  draft: false
                  prerelease: false
                  files: |
                      wallhaven-cli*
