name: Release Application
on:
    push:
        paths:
            - 'version'

    workflow_dispatch:

permissions:
    contents: write

jobs:
    publish:
        name: Release app
        runs-on: ubuntu-latest
        steps:
            - name: Clone codebase
              uses: actions/checkout@v4

            - name: Get tag name
              id: tag
              run: echo "version=$(cat version)" >> $GITHUB_OUTPUT

            - name: Release asset
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.tag.outputs.version }}
                  draft: false
                  prerelease: false
